### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Rinalusi44** [codecov/feedback#238]
**What product do you want to improve?**
(e.g., Uploader, Web application, CLI, browser extension, Slack App, etc)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/feedback/issues/118
- [ ] Rinalusi44s
- [ ] https://github.com/codecov/feedback/issues/237
- [ ] https://github.com/codecov/feedback/issues/123
- [ ] https://github.com/codecov/feedback/issues/235
```

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/feedback/issues/123
```
