### ISSUE TITLE
"Guest Access" feature not functional

### ISSUE THREAD

**Issue by jerrodcodecov** [codecov/feedback#252]
**Describe the bug**
An enterprise customer uses "not-private" repos in their private Github Enterprise Server on-prem (behind a firewall), e.g., an "open source" repo that contains private IP. They felt comfortable doing this because they knew their Github Enterprise Server would not be exposed to open internet

However their Codecov instance is not behind a firewall, and they are worried about an attack vector of someone resolving their URL to view the "not-private" repos on their Codecov self-hosted and/or Dedicated Enterprise Cloud instance.

Historically, Codecov had a feature called `Guest Access` to prevent access to the instance at all / open source repos from showing up on an Enterprise version of Codecov (self-hosted). 

https://docs.codecov.com/docs/configuration#guest-access

That feature is no longer working.

**Environment (please complete the following information):**
 - Codecov Self-hosted and Dedicated Enterprise Cloud without a firewall

**To Reproduce**

[Will publish an enterprise URL in question on a private channel]

OR
1. On a self-hosted environment
2. Add to system yaml

```
setup:
  guest_access: off
```
  
3. As a logged out user, visit that URL -- see all non-private repos (active or inactive) repos and see instance generally.

**Expected behavior**
3. When `guest_access` is `off` then a logged in user cannot see instance at all.

**Screenshots**
[not applicable due to customer privacy]

**Additional context**
Further discussion in Slack 

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1243
- [ ] https://github.com/codecov/feedback/issues/297
- [ ] https://github.com/codecov/feedback/issues/298
- [ ] https://github.com/codecov/feedback/issues/319
```

**Comment by jerrodcodecov** [comment]
From a basic code query, it doesn't appear this feature has been part of the self-hosted yaml since the `codecov.io` monorepo, although the documentation remained as did the example yaml in the /enterprise repo

<img width="882" alt="image" src="https://github.com/codecov/feedback/assets/88494665/20bb5484-3f39-47a7-8bc3-d46ae25fe344">

**Comment by jerrodcodecov** [comment]
@rohan-at-sentry seeking an update here, thanks!

**Comment by rohan-at-sentry** [comment]
marking this as a "bug" so we can talk about it in this week's bug synch

**Comment by rohan-at-sentry** [comment]
https://sentry.slack.com/archives/C04MJP65Z2M/p1706626113674569

**Comment by RulaKhaled** [comment]
blocked by https://github.com/codecov/engineering-team/issues/1243

**Comment by RulaKhaled** [comment]
We had to revert because we added a middleware preventing all unauthorized access except for login and health requests, but some other endpoints needed to allow guest access at all times. I'm working on a better fix and aim to ship this next week.

**Comment by RulaKhaled** [comment]
It was fine it was only shipped internally with no new enterprise releases so it effected no customers, right now i have https://github.com/codecov/codecov-api/pull/458 approved but we were waiting for the launch week to be over as it's considered an experimental change, i plan to give this early next week, i will keep you updated
